"""BibTeX subset export — copy only the cited entries from sources.bib.

Why a subset, not the full file?
    Strict-Quellen is the USP of this tool. Shipping a 100-entry
    sources.bib alongside one V–I-CSV is noise. A 5-entry .bib file
    that exactly matches what the current design point uses is the
    receipt that says: "these are the cited papers behind these numbers".

The parser is minimal — splits the file on top-level `@...{key,` lines
and keeps the matching blocks. A full BibTeX parser is overkill for
the library/sources.bib we control.
"""

from __future__ import annotations

import re
from pathlib import Path


# Matches the opening line of a BibTeX entry: @article{key,
# Allow whitespace around the key, capture the key.
_ENTRY_HEADER = re.compile(r"^@(\w+)\s*\{\s*([^,\s]+)\s*,", re.MULTILINE)


def split_bibtex_entries(bib_text: str) -> dict[str, str]:
    """Parse `bib_text` into {key: raw-entry-block-text}.

    The "block" extends from the `@type{key,` line to the matching
    closing `}` at column 0. Comments outside entries are dropped.
    """
    entries: dict[str, str] = {}
    matches = list(_ENTRY_HEADER.finditer(bib_text))
    for i, m in enumerate(matches):
        key = m.group(2)
        start = m.start()
        # Walk forward to find the matching closing brace.
        depth = 0
        end = start
        for j, ch in enumerate(bib_text[start:], start=start):
            if ch == "{":
                depth += 1
            elif ch == "}":
                depth -= 1
                if depth == 0:
                    end = j + 1
                    break
        else:
            # Unmatched — should not happen with a well-formed file.
            end = matches[i + 1].start() if i + 1 < len(matches) else len(bib_text)
        entries[key] = bib_text[start:end]
    return entries


def render_bibtex_subset(bib_text: str, keys: set[str]) -> str:
    """Return a new BibTeX document containing only the entries in `keys`.

    Missing keys are silently dropped — the caller can compare its input
    set against the parsed-keys set to detect that.
    """
    all_entries = split_bibtex_entries(bib_text)
    header = "% Subset of library/sources.bib generated by pem-ec-designer.\n"
    header += f"% {len(keys & all_entries.keys())} of {len(keys)} requested entries found.\n\n"
    parts = [all_entries[k] for k in sorted(keys) if k in all_entries]
    return header + "\n\n".join(parts) + ("\n" if parts else "")


def write_bibtex_subset(bib_path: Path, keys: set[str], out_path: Path) -> set[str]:
    """Write the subset .bib to disk; return the set of keys actually found.

    Caller can check `found != requested` to surface "X cited keys were not
    in sources.bib" in the UI.
    """
    bib_path = Path(bib_path)
    out_path = Path(out_path)
    text = bib_path.read_text(encoding="utf-8")
    out_path.parent.mkdir(parents=True, exist_ok=True)
    out_path.write_text(render_bibtex_subset(text, keys), encoding="utf-8")
    found = set(split_bibtex_entries(text).keys()) & keys
    return found
